<a href="https://colab.research.google.com/github/tejpal123456789/Natural-Language-Processing/blob/main/language_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import pandas as pd
import tensorflow as tf

!git clone https://github.com/suvaansh/Machine-Translation-English-to-Hindi-.git


fatal: destination path 'Machine-Translation-English-to-Hindi-' already exists and is not an empty directory.


In [ ]:
data=pd.read_csv('/content/Machine-Translation-English-to-Hindi-/hin.txt',sep='\t',header=None)
data.head()


0        1
0   Help!    बचाओ!
1   Jump.    उछलो.
2   Jump.    कूदो.
3   Jump.   छलांग.
4  Hello!  नमस्ते।

In [ ]:
data.shape

(2869, 2)

In [ ]:
data.tail()

0                                                  1
2864  The passengers who were injured in the acciden...  जिन यात्रियों को दुर्घटना मे चोट आई थी उन्हे अ...
2865  Democracy is the worst form of government, exc...  लोकतंत्र सरकार का सबसे घिनौना रूप है, अगर बाकी...
2866  If my boy had not been killed in the traffic a...  अगर मेरा बेटा ट्रेफ़िक हादसे में नहीं मारा गया...
2867  When I was a kid, touching bugs didn't bother ...  जब मैं बच्चा था, मुझे कीड़ों को छूने से कोई पर...
2868  Make a good translation of the sentence that y...  आप जिस वाक्य का अनुवाद कर रहे हैं, उस ही का अच...

In [ ]:
hindi_data=data.iloc[:,1]
hindi_data.head()
data1=data.iloc[:,0].append(hindi_data)
data1.reset_index

<bound method Series.reset_index of 0                                                   Help!
1                                                   Jump.
2                                                   Jump.
3                                                   Jump.
4                                                  Hello!
                              ...                        
2864    जिन यात्रियों को दुर्घटना मे चोट आई थी उन्हे अ...
2865    लोकतंत्र सरकार का सबसे घिनौना रूप है, अगर बाकी...
2866    अगर मेरा बेटा ट्रेफ़िक हादसे में नहीं मारा गया...
2867    जब मैं बच्चा था, मुझे कीड़ों को छूने से कोई पर...
2868    आप जिस वाक्य का अनुवाद कर रहे हैं, उस ही का अच...
Length: 5738, dtype: object>

In [ ]:
data1.head()

0     Help!
1     Jump.
2     Jump.
3     Jump.
4    Hello!
dtype: object

In [ ]:
data1.shape

(5738,)

In [ ]:
data1.tail()

2864    जिन यात्रियों को दुर्घटना मे चोट आई थी उन्हे अ...
2865    लोकतंत्र सरकार का सबसे घिनौना रूप है, अगर बाकी...
2866    अगर मेरा बेटा ट्रेफ़िक हादसे में नहीं मारा गया...
2867    जब मैं बच्चा था, मुझे कीड़ों को छूने से कोई पर...
2868    आप जिस वाक्य का अनुवाद कर रहे हैं, उस ही का अच...
dtype: object

In [ ]:
data1.shape

(5738,)

In [ ]:
data2=pd.DataFrame(data=data1)
data2.head()
data2.reset_index(inplace=True)
data2.tail()

index                                                  0
5733   2864  जिन यात्रियों को दुर्घटना मे चोट आई थी उन्हे अ...
5734   2865  लोकतंत्र सरकार का सबसे घिनौना रूप है, अगर बाकी...
5735   2866  अगर मेरा बेटा ट्रेफ़िक हादसे में नहीं मारा गया...
5736   2867  जब मैं बच्चा था, मुझे कीड़ों को छूने से कोई पर...
5737   2868  आप जिस वाक्य का अनुवाद कर रहे हैं, उस ही का अच...

In [ ]:
data2['language_type']='language'
data2.head()

index       0 language_type
0      0   Help!      language
1      1   Jump.      language
2      2   Jump.      language
3      3   Jump.      language
4      4  Hello!      language

In [ ]:
data2['language_type'].loc[0:2868]='english'
data2.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


index       0 language_type
0      0   Help!       english
1      1   Jump.       english
2      2   Jump.       english
3      3   Jump.       english
4      4  Hello!       english

In [ ]:
data2['language_type'].loc[2869:5738]='hindi'
data2.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)


index       0 language_type
0      0   Help!       english
1      1   Jump.       english
2      2   Jump.       english
3      3   Jump.       english
4      4  Hello!       english

In [ ]:
data2['language_type'].value_counts()

english    2869
hindi      2869
Name: language_type, dtype: int64

In [ ]:
data2.drop(['index'],axis=1,inplace=True)
data2.head()

0 language_type
0   Help!       english
1   Jump.       english
2   Jump.       english
3   Jump.       english
4  Hello!       english

In [ ]:
columns=['languages','language_type']
data2.columns=columns
data2.head()

languages language_type
0     Help!       english
1     Jump.       english
2     Jump.       english
3     Jump.       english
4    Hello!       english

In [ ]:
mapping={'english': 0, 'hindi': 1}
data2['language_type']=data2['language_type'].apply(lambda x: 0 if x=='english' else 1)
data2.head()


languages  language_type
0     Help!              0
1     Jump.              0
2     Jump.              0
3     Jump.              0
4    Hello!              0

In [ ]:
data2['language_type'].value_counts()

1    2869
0    2869
Name: language_type, dtype: int64

In [ ]:
import string
for char in string.punctuation:
    print(char, end=' ')
    

! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~ 

Cleaning of the whole data 

In [ ]:
def clean_text(doc):
  tokens = doc.split()
  table = str.maketrans('', '', string.punctuation)  
  tokens = [w.translate(table) for w in tokens]
  tokens = [word.lower() for word in tokens]
  sentence=' '.join(tokens)
  return sentence

In [ ]:
x='i am a ! tejpal kumwat/....'
y=clean_text(x)
print(y)

i am a  tejpal kumwat


In [ ]:
data2['languages']=data2['languages'].apply(lambda x: clean_text(x))
data2.tail()

languages  language_type
5733  जिन यात्रियों को दुर्घटना मे चोट आई थी उन्हे अ...              1
5734  लोकतंत्र सरकार का सबसे घिनौना रूप है अगर बाकी ...              1
5735  अगर मेरा बेटा ट्रेफ़िक हादसे में नहीं मारा गया...              1
5736  जब मैं बच्चा था मुझे कीड़ों को छूने से कोई परे...              1
5737  आप जिस वाक्य का अनुवाद कर रहे हैं उस ही का अच्...              1

In [ ]:
# shuffle the DataFrame rows 
data2 = data2.sample(frac = 1) 
  
# print the shuffled DataFrame 
print("\nShuffled DataFrame:") 
data2.head()


Shuffled DataFrame:


languages  language_type
1562               i have a bone to pick with you              0
564                            ill admit im wrong              0
2508  the thief cursed the police for finding him              0
3118                                    मज़े करो।              1
389                             i still dont know              0

In [ ]:
x=data2['languages']
y=data2['language_type']


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
cv=CountVectorizer(5000)
x_trained=cv.fit_transform(x_train).toarray()

print(x_trained.shape)
print(y_train.shape)



x_tested=cv.transform(x_test).toarray()
print(x_tested.shape)



(4590, 2781)
(4590,)
(1148, 2781)


In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
#model=lr.fit(x_trained,y_train)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
#y_pred=model.predict(x_tested)
#print('accuracy of the model is {}'.format(accuracy_score(y_test,y_pred)))
#print('Confusion matrix of the model is {}'.format(confusion_matrix(y_test,y_pred)))

Now we will predict the language type for any general text of hindi and english

Saving the model

In [ ]:
#import pickle
#pickle.dump(model,open('language_detection.pkl','wb'))

In [ ]:

def predict_language(input):
    def clean_text(input):
      tokens = input.split()
      table = str.maketrans('', '', string.punctuation)  
      tokens = [w.translate(table) for w in tokens]
      tokens = [word.lower() for word in tokens]
      sentence=' '.join(tokens)
      return sentence
    model1=pickle.load(open('/content/language_detection.pkl','rb'))  
    
    predict=model1.predict([[clean_text(input)]])

    return predict


    

Word Embedding

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding,Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size=30000
onehot_repr=[one_hot(words,voc_size)for words in data2['languages']] 
onehot_repr

sent_length=20

embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[    0     0     0 ... 10456 19187 21119]
 [    0     0     0 ...  5601  3698  1288]
 [    0     0     0 ... 12153 19488  5082]
 ...
 [    0     0     0 ... 18891  2375 26396]
 [    0     0     0 ...  7577  7287 13153]
 [    0     0     0 ... 22235  6194 16198]]


In [ ]:
#text=['my name is tejpal kumawat']
#voc_size=30000
#onehot_repr=[one_hot(words,voc_size)for words in text]
#onehot_repr

#sent_length=20

#embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
#print(embedded_docs)


In [ ]:
embedded_docs.shape

(5738, 20)

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(data2['language_type'])

print(X_final.shape,y_final.shape)


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

(5738, 20) (5738,)


In [ ]:
embed_dim = 128
lstm_out = 200
batch_size = 32

model = Sequential()
model.add(Embedding(voc_size, embed_dim,input_length = X_train.shape[1]))
model.add(LSTM(lstm_out)) 
model.add(Dense(1,activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())



Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 20, 128)           3840000   
_________________________________________________________________
lstm_2 (LSTM)                (None, 200)               263200    
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 201       
Total params: 4,103,401
Trainable params: 4,103,401
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
61/61 [==============================] - 11s 144ms/step - loss: 0.5018 - accuracy: 0.7756 - val_loss: 0.0966 - val_accuracy: 0.9931
Epoch 2/10
61/61 [==============================] - 8s 136ms/step - loss: 0.0509 - accuracy: 0.9968 - val_loss: 0.0174 - val_accuracy: 0.9942
Epoch 3/10
61/61 [==============================] - 8s 137ms/step - loss: 0.0078 - accuracy: 0.9990 - val_loss: 0.0117 - val_accuracy: 0.9974
Epoch 4/10
61/61 [==============================] - 8s 139ms/step - loss: 0.0055 - accuracy: 0.9989 - val_loss: 0.0091 - val_accuracy: 0.9958
Epoch 5/10
61/61 [==============================] - 8s 137ms/step - loss: 0.0031 - accuracy: 0.9992 - val_loss: 0.0129 - val_accuracy: 0.9952
Epoch 6/10
61/61 [==============================] - 8s 136ms/step - loss: 0.0038 - accuracy: 0.9993 - val_loss: 0.0081 - val_accuracy: 0.9952
Epoch 7/10
61/61 [==============================] - 8s 138ms/step - loss: 0.0013 - accuracy: 1.0000 - val_loss: 0.0079 - val_accuracy: 0.9958
Epoch

In [ ]:
y_pred=model.predict(X_test)
print(y_pred.shape)
y_pred1=[]
for i in range(1894):
    if y_pred[i][0]>=0.5:
        y_pred1.append(1)
    else:
        y_pred1.append(0)    
print(y_pred1)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred1))
print(y_test)


(1894, 1)
[1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,

In [ ]:
from keras.models import load_model

model.save('my_model.h5')  # creates a HDF5 file 'my_model.h5'
del model  # deletes the existing model

# returns a compiled model
# identical to the previous one
model = load_model('my_model.h5')

In [ ]:
#model=load_model('Spam_classifier.h5',compile=False)

#st.title('SPAM MAIL CLASSIFIER')
#st.image('download.jpg',width=500)
voc_size=30000
sent_length = 20

#st.header('Give the Input as a Mail to check whether it is a spam or not')
#input=st.text_input('Write the text here')
#input_data=list(input)
import re
def input_preprocessing(x):
    corpus = []

    review = re.sub('[^a-zA-z]', ' ', str(x))
    review = review.lower()
    review = review.split()
    #review = [wnl.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

    onehot_repr = [one_hot(words, voc_size) for words in corpus]


    embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
    X=np.array(embedded_docs)
    
    return X
input_data=['  लोग रहें ']
x=input_preprocessing(input_data)
prediction = model.predict(x)
print(prediction) 

[[0.3551969]]


In [ ]:

import numpy as np
if prediction[0][0] >=0.5:
    print('language is hindi')
else:
    print('language is english')        

language is english
