<a href="https://colab.research.google.com/github/tejpal123456789/Natural-Language-Processing/blob/main/spam_classifer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/data_deep_learning/spam_classifier.csv',encoding = "ISO-8859-1")
data.head()

v1  ... Unnamed: 4
0   ham  ...        NaN
1   ham  ...        NaN
2  spam  ...        NaN
3   ham  ...        NaN
4   ham  ...        NaN

[5 rows x 5 columns]

In [ ]:
data1=data.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)
data1.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
data1.isnull().sum()

v1    0
v2    0
dtype: int64

In [ ]:
import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
ps = PorterStemmer()
wnl=WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
x=data1.drop(['v1'],axis=1)
y=data1['v1']

In [ ]:
name='hello world'
lst=list(name)
print(lst)

['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']


Preprocessing of the text data

In [ ]:
corpus=[]
for i in range(len(x)):
    review=re.sub('[^a-zA-z]',' ',str(x['v2'][i]))
    review=review.lower()
    review=review.split()
    review=[wnl.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)
#print(corpus)    

print(review)
corpus[-1]

rofl true name


'rofl true name'

In [ ]:
print(corpus)

['go jurong point crazy available bugis n great world la e buffet cine got amore wat', 'ok lar joking wif u oni', 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply', 'u dun say early hor u c already say', 'nah think go usf life around though', 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv', 'even brother like speak treat like aid patent', 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune', 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour', 'mobile month u r entitled update latest colour mobile camera free call mobile update co free', 'gonna home soon want talk stuff anymore tonight k cried enough today', 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info', 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw', 'searching

Converting into vectors by Bag of Words

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
xx=cv.fit_transform(corpus)
Y=pd.get_dummies(y,drop_first=True)
Y=np.array(Y)
#print(xx)
Y.reshape(-1,1)
y.shape

(5572,)

Using Machine Learning Algorithm

Making vectors by lemmetizer

Predicting By Using Reccurent Neural Network (LSTM)

Word Embedding

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding,Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense


In [ ]:
voc_size=10000
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[9351,
  1315,
  1354,
  1368,
  9756,
  4393,
  3971,
  517,
  657,
  2132,
  4441,
  5148,
  9123,
  9823,
  366,
  25],
 [4691, 764, 8577, 187, 3469, 7325],
 [9249,
  2862,
  9878,
  7295,
  755,
  4041,
  4366,
  3377,
  472,
  6530,
  6438,
  1873,
  4041,
  2677,
  2862,
  3786,
  5630,
  933,
  5555,
  6204,
  1559],
 [3469, 8156, 5232, 4720, 3088, 3469, 6204, 5277, 5232],
 [759, 8115, 9351, 4218, 4450, 2065, 9001],
 [9807,
  3311,
  7367,
  7476,
  6938,
  7692,
  3856,
  6207,
  1137,
  683,
  4691,
  4611,
  5630,
  5953,
  4611,
  2852],
 [4234, 3499, 3856, 3828, 6930, 3856, 1858, 6969],
 [2276,
  6903,
  8312,
  8312,
  7032,
  783,
  863,
  8114,
  6881,
  6461,
  438,
  9483,
  818,
  6812,
  6461],
 [4242,
  6210,
  2623,
  2223,
  2745,
  5062,
  7434,
  2460,
  6515,
  2188,
  6515,
  5910,
  6410,
  7999,
  487],
 [5801,
  2488,
  3469,
  9576,
  5395,
  617,
  9101,
  8641,
  5801,
  9155,
  9249,
  2188,
  5801,
  617,
  1621,
  9249],
 [5609, 2779, 1302, 7834, 174

In [ ]:

sent_length=20

embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 9823  366   25]
 [   0    0    0 ...  187 3469 7325]
 [2862 9878 7295 ... 5555 6204 1559]
 ...
 [   0    0    0 ... 8572 6885  132]
 [   0    0    0 ... 7698 3469 9249]
 [   0    0    0 ... 1161 9147 2635]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0, 9351, 1315, 1354, 1368, 9756, 4393, 3971,
        517,  657, 2132, 4441, 5148, 9123, 9823,  366,   25], dtype=int32)

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(Y)

print(X_final.shape,y_final.shape)


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

(5572, 20) (5572, 1)


In [ ]:
embed_dim = 128
lstm_out = 200
batch_size = 32

model = Sequential()
model.add(Embedding(voc_size, embed_dim,input_length = X_train.shape[1]))
model.add(LSTM(lstm_out))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss = 'binary_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 128)           1280000   
_________________________________________________________________
lstm (LSTM)                  (None, 200)               263200    
_________________________________________________________________
dense (Dense)                (None, 1)                 201       
Total params: 1,543,401
Trainable params: 1,543,401
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
59/59 [==============================] - 8s 109ms/step - loss: 0.3639 - accuracy: 0.8800 - val_loss: 0.0807 - val_accuracy: 0.9810
Epoch 2/10
59/59 [==============================] - 6s 97ms/step - loss: 0.0523 - accuracy: 0.9844 - val_loss: 0.0605 - val_accuracy: 0.9848
Epoch 3/10
59/59 [==============================] - 6s 96ms/step - loss: 0.0132 - accuracy: 0.9965 - val_loss: 0.0686 - val_accuracy: 0.9853
Epoch 4/10
59/59 [==============================] - 6s 98ms/step - loss: 0.0050 - accuracy: 0.9994 - val_loss: 0.0679 - val_accuracy: 0.9869
Epoch 5/10
59/59 [==============================] - 6s 98ms/step - loss: 0.0037 - accuracy: 0.9996 - val_loss: 0.0714 - val_accuracy: 0.9799
Epoch 6/10
59/59 [==============================] - 6s 98ms/step - loss: 0.0036 - accuracy: 0.9995 - val_loss: 0.0913 - val_accuracy: 0.9837
Epoch 7/10
59/59 [==============================] - 6s 99ms/step - loss: 0.0019 - accuracy: 0.9994 - val_loss: 0.0807 - val_accuracy: 0.9837
Epoch 8/10
5

In [ ]:
model.save('Spam_classifier.h5')